version: 2
jobs:
  build:
    docker:
      - image: liuchong/rustup
    steps:
      - checkout
      - run: rustup default nightly
      - run: apt-get update -y
      - run: apt-get install -y cmake
      - run:
          name: Run tests
          command: cargo test
