version: 2
jobs:
  build:
    docker:
      - image: saltyrtc/circleci-image-rs
    steps:
      - checkout
      - run: rustup toolchain add nightly
      - run: rustup default nightly
      - run: rustup update
      - run:
          name: Run tests
          command: cargo test
